services:
  django:
    build: ./server
    depends_on:
      - redis
      - db
    expose:
      - "8000"
    env_file:
      - .env
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    expose:
      - "6379"
    restart: unless-stopped

  db:
    image: postgres:17-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped
  
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      - django
    expose:
      - "80"
    env_file:
    - .env
    networks:
      default:
      proxy_network:
        aliases:
          - battleship-nginx
    restart: unless-stopped


volumes:
  db-data:

networks:
  proxy_network:
    external: true