# Generated by Django 5.2 on 2026-08-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_board_id_alter_coordinate_id_alter_game_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_human',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='channel_name',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
