# Generated by Django 5.2 on 2026-08-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_player_is_human_alter_player_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='available_since',
            field=models.DateTimeField(null=True),
        ),
    ]
